#ifndef PROMPT_EDITOR_H
#define PROMPT_EDITOR_H

// Auto-generated by cbindgen. Do not edit.

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Copy text to system clipboard. Returns 0 on success, -1 on error.
 */
int32_t pe_clipboard_copy(const char *text);

/**
 * Get clipboard text. Caller must free the returned string with pe_free_string.
 */
char *pe_clipboard_get(void);

/**
 * Save a prompt to storage. Returns the prompt ID (>0) on success, -1 on error.
 */
int64_t pe_save_prompt(const char *title, const char *content);

/**
 * Convert markdown to HTML. Caller must free with pe_free_string.
 */
char *pe_markdown_to_html(const char *md);

/**
 * Free a string returned by this library.
 */
void pe_free_string(char *s);

/**
 * Scan a directory and return JSON array of files.
 * Returns NULL on error. Caller must free with pe_free_string.
 */
char *pe_scan_directory(const char *path);

/**
 * Read file content.
 * Returns NULL on error. Caller must free with pe_free_string.
 */
char *pe_read_file(const char *path);

/**
 * Search files in last scanned directory.
 * Returns JSON array. Caller must free with pe_free_string.
 */
char *pe_search_files(const char *query);

/**
 * Get scanned files count.
 */
int32_t pe_get_scanned_files_count(void);

/**
 * Clear file cache.
 */
void pe_clear_file_cache(void);

/**
 * List all templates as JSON. Caller must free with pe_free_string.
 */
char *pe_list_templates(void);

/**
 * Save a template from JSON. Returns 0 on success, -1 on error.
 */
int32_t pe_save_template(const char *json);

/**
 * Delete a template by ID. Returns 0 on success, -1 on error.
 */
int32_t pe_delete_template(const char *id);

/**
 * List all data sources as JSON. Caller must free with pe_free_string.
 */
char *pe_list_data_sources(void);

/**
 * Save a data source from JSON. Returns 0 on success, -1 on error.
 */
int32_t pe_save_data_source(const char *json);

/**
 * Delete a data source by ID. Returns 0 on success, -1 on error.
 */
int32_t pe_delete_data_source(const char *id);

#endif /* PROMPT_EDITOR_H */
